name: Containerized Train CI/CD
run-name: Train CI/CD
on: [push]
jobs:
  BuildAndPushDockerImage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            mbouzayeni/train-schedule:${{ github.sha }}
          cache-from: type=registry,ref=user/app:buildcache
          cache-to: type=registry,ref=user/app:buildcache,mode=max              
  DeployToKubernetes:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: PushDockerImage
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: <server-url> ## TODO
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }} ## TODO

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Replace the variables in the kubernetes config file
        uses: cschleiden/replace-tokens@v1
        with:
          files: [train-schedule-kube.yaml]
          tokenPrefix: __
          tokenSuffix: __
        env:
          DOCKER_IMAGE_NAME: mbouzayeni/train-schedule
          BUILD_NUMBER: ${{ github.sha }}

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            train-schedule-kube.yml